In [1]:
from google.colab import files
uploaded = files.upload()

Saving hospital_operations_dataset.csv to hospital_operations_dataset.csv

In [2]:
import pandas as pd

df = pd.read_csv('hospital_operations_dataset.csv')

df.head()

,Patient_ID,Visit_Date,Age,Gender,Disease,Severity,Admission_Type,Length_of_Stay,Bed_Required,ICU_Required,...,Total_Beds_Available,Beds_Occupied,ICU_Beds_Available,ICU_Beds_Occupied,Oxygen_Units_Used,Month,Season,Day_of_Week,Department,Readmission_Within_30_Days
0,P00624,21-03-2023,63,Male,Food Poisoning,Mild,OPD,0.0,No,No,...,247,156,19,9,3.0,3,Spring,Tuesday,Gastroenterology,No
1,P02862,04-03-2023,44,Male,Liver Disease,Severe,Emergency,9.0,No,No,...,145,92,28,13,4.0,3,Spring,Saturday,Gastroenterology,No
2,P01271,10-11-2024,52,Female,Anemia,Moderate,Inpatient,2.0,Yes,No,...,105,62,20,9,1.0,11,Autumn,Sunday,General Medicine,Yes
3,P02681,27-02-2023,63,Male,Thyroid Disorder,Moderate,OPD,0.0,No,No,...,203,136,21,13,1.0,2,Winter,Monday,General Medicine,No
4,P04980,09-07-2023,72,Male,Heart Disease,Severe,Emergency,11.0,Yes,Yes,...,194,118,31,12,2.0,7,Monsoon,Sunday,ICU,No

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5075 entries, 0 to 5074
Data columns (total 22 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Patient_ID                  5075 non-null   object
 1   Visit_Date                  5075 non-null   object
 2   Age                         5075 non-null   int64
 3   Gender                      4972 non-null   object
 4   Disease                     5075 non-null   object
 5   Severity                    5075 non-null   object
 6   Admission_Type              5075 non-null   object
 7   Length_of_Stay              5025 non-null   float64
 8   Bed_Required                5075 non-null   object
 9   ICU_Required                5075 non-null   object
 10  Oxygen_Required             5075 non-null   object
 11  Ventilator_Required         5075 non-null   object
 12  Total_Beds_Available        5075 non-null   int64
 13  Beds_Occupied               5075 non-null   int64
 14  ICU_Beds_Available          5075 non-null   int64
 15  ICU_Beds_Occupied           5075 non-null   int64
 16  Oxygen_Units_Used           4975 non-null   float64
 17  Month                       5075 non-null   int64
 18  Season                      5075 non-null   object
 19  Day_of_Week                 5075 non-null   object
 20  Department                  4998 non-null   object
 21  Readmission_Within_30_Days  5075 non-null   object
dtypes: float64(2), int64(6), object(14)
memory usage: 872.4+ KB

In [4]:
df.shape

(5075, 22)

In [5]:
df.isnull().sum()

Patient_ID                      0
Visit_Date                      0
Age                             0
Gender                        103
Disease                         0
Severity                        0
Admission_Type                  0
Length_of_Stay                 50
Bed_Required                    0
ICU_Required                    0
Oxygen_Required                 0
Ventilator_Required             0
Total_Beds_Available            0
Beds_Occupied                   0
ICU_Beds_Available              0
ICU_Beds_Occupied               0
Oxygen_Units_Used             100
Month                           0
Season                          0
Day_of_Week                     0
Department                     77
Readmission_Within_30_Days      0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(75)

In [7]:
# Remove duplicates
df = df.drop_duplicates()

# Fill missing values
df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])

df['Department'] = df['Department'].fillna(df['Department'].mode()[0])

df['Length_of_Stay'] = df['Length_of_Stay'].fillna(df['Length_of_Stay'].median())

df['Oxygen_Units_Used'] = df['Oxygen_Units_Used'].fillna(df['Oxygen_Units_Used'].median())

# Standardize text columns
text_columns = ['Gender','Severity','Admission_Type','Department','Day_of_Week']

for col in text_columns:
    df[col] = df[col].astype(str).str.strip().str.title()

print("Cleaning Completed Successfully!")

Cleaning Completed Successfully!

In [8]:
df.isnull().sum()

Patient_ID                    0
Visit_Date                    0
Age                           0
Gender                        0
Disease                       0
Severity                      0
Admission_Type                0
Length_of_Stay                0
Bed_Required                  0
ICU_Required                  0
Oxygen_Required               0
Ventilator_Required           0
Total_Beds_Available          0
Beds_Occupied                 0
ICU_Beds_Available            0
ICU_Beds_Occupied             0
Oxygen_Units_Used             0
Month                         0
Season                        0
Day_of_Week                   0
Department                    0
Readmission_Within_30_Days    0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
# Create Age Group

df['Age_Group'] = pd.cut(
    df['Age'],
    bins=[0,18,40,60,100],
    labels=['Child','Young Adult','Adult','Senior']
)

# Create Bed Occupancy Rate

df['Occupancy_Rate'] = (
    df['Beds_Occupied'] /
    df['Total_Beds_Available']
) * 100

df[['Age','Age_Group','Occupancy_Rate']].head()

   Age Age_Group  Occupancy_Rate
0   63    Senior       63.157895
1   44     Adult       63.448276
2   52     Adult       59.047619
3   63    Senior       66.995074
4   72    Senior       60.824742

In [11]:
print("Total Patients:", len(df))
print("Average Length of Stay:", round(df['Length_of_Stay'].mean(),2))
print("Average Oxygen Usage:", round(df['Oxygen_Units_Used'].mean(),2))
print("Total Departments:", df['Department'].nunique())
print("Total Beds Occupied:", df['Beds_Occupied'].sum())
print("Total ICU Beds Occupied:", df['ICU_Beds_Occupied'].sum())

Total Patients: 5000
Average Length of Stay: 5.09
Average Oxygen Usage: 38.45
Total Departments: 8
Total Beds Occupied: 546147
Total ICU Beds Occupied: 62774

In [12]:
df.to_csv("hospital_cleaned_dataset.csv", index=False)

In [13]:
from google.colab import files
files.download("hospital_cleaned_dataset.csv")

In [14]:
df.to_csv("hospital_cleaned_dataset.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [15]:
from google.colab import files
files.download("hospital_cleaned_dataset.csv")

In [16]:
print("Missing Values:")
print(df.isnull().sum().sum())

print("Duplicate Records:")
print(df.duplicated().sum())

Missing Values:
8
Duplicate Records:
0

In [17]:
df.isnull().sum()

Patient_ID                    0
Visit_Date                    0
Age                           0
Gender                        0
Disease                       0
Severity                      0
Admission_Type                0
Length_of_Stay                0
Bed_Required                  0
ICU_Required                  0
Oxygen_Required               0
Ventilator_Required           0
Total_Beds_Available          0
Beds_Occupied                 0
ICU_Beds_Available            0
ICU_Beds_Occupied             0
Oxygen_Units_Used             0
Month                         0
Season                        0
Day_of_Week                   0
Department                    0
Readmission_Within_30_Days    0
Age_Group                     8
Occupancy_Rate                0
dtype: int64

In [18]:
df = df.dropna()

In [19]:
print("Missing Values:")
print(df.isnull().sum().sum())

print("Duplicate Records:")
print(df.duplicated().sum())

Missing Values:
0
Duplicate Records:
0